title: "Yu Kobayashi"
description: "Full-time MBA Candidate at Berkeley Haas ’27 interested in venture investing and agricultural technology."
url: "https://yukobayashi0811.github.io"
baseurl: ""
lang: en
timezone: America/Los_Angeles

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - PLAN.md
  - Change1.md
  - Gemfile
  - Gemfile.lock
  - vendor
